usuarios/applications/home/urls.py
from django.urls import path

from . import views

app_name = 'home_app'

urlpatterns = [
    path(
        'panel/',
        views.HomePage.as_view(),
        name='panel'
    ),
    path(
        'mixin/',
        views.TemplatePruebaMixin.as_view(),
        name='mixin'
    ),
]

usuarios/applications/users/urls.py
from django.urls import path

from . import views

app_name = 'users_app'

urlpatterns = [
    path(
        'register/',
        views.UserRegisterViews.as_view(),
        name='user-register'
    ),
    path(
            'login/',
            views.LoginUser.as_view(),
            name='user-login'
        ),
    path(
            'logout/',
            views.LogoutView.as_view(),
            name='user-logout'
    ),
    path(
            'update/',
            views.UpdatePasswordView.as_view(),
            name='user-update'
    ),
    path(
            'user-verification/<pk>/',
            views.CodeVerificationView.as_view(),
            name='user-verification'
    ),
]

usuarios/usuarios/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
]

usuarios/applications/home/models.py
from django.db import models

# Create your models here.

usuarios/applications/home/views.py
import datetime
#
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    TemplateView
)

class FechaMixin(object):
    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context['fecha'] = datetime.datetime.now()
        return context


class HomePage(LoginRequiredMixin, FechaMixin, TemplateView):
    template_name = 'home/index.html'
    login_url = reverse_lazy('users_app:user-login')


class TemplatePruebaMixin(FechaMixin, TemplateView):
    template_name = 'home/mixin.html'

usuarios/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  <h1>Panel de usuario</h1>
  <h1>Bienvenido, {{ user }}</h1>
  <p>Fecha:   {{ fecha }}</p>
  <ul>
    <li><a href="{% url 'users_app:user-logout' %}">Cerrar sesion</a></li>
    <li><a href="{% url 'users_app:user-update' %}">actualizar datos</a> </li>
  </ul>
</body>
</html>

usuarios/templates/home/mixin.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Mixibg</title>
</head>
<body>
  <h1>Probando Mixin</h1>
  {{ fecha }}
</body>
</html>